{
 "title": "Argo CD",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Applications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(argocd_app_info) by (project)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"Synced\"}) by (sync_status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(argocd_app_info{sync_status=\"OutOfSync\"}) by (sync_status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(argocd_app_info{sync_status=\"Unknown\"}) by (sync_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(argocd_app_info{health_status=\"Healthy\"}) by (health_status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(argocd_app_info{health_status=\"Progressing\"}) by (health_status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(argocd_app_info{health_status=\"Degraded\"}) by (health_status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(argocd_app_info{health_status=\"Missing\"}) by (health_status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(argocd_app_info{health_status=\"Suspended\"}) by (health_status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(argocd_app_info{health_status=\"Unknown\"}) by (health_status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}