{
 "title": "Homelab",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes) * 100) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m15s])) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum((node_memory_MemTotal_bytes - node_memory_MemFree_bytes) / node_memory_MemTotal_bytes) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(irate(node_cpu_seconds_total{instance=\"s-bear\",mode=\"idle\"}[1m15s])) / scalar(count(count(node_cpu_seconds_total{instance=\"s-bear\"}) by (cpu)))",
     "legendFormat": "s-bear"
    },
    {
     "expr": "1 - sum(irate(node_cpu_seconds_total{instance=\"s-shark\",mode=\"idle\"}[1m15s])) / scalar(count(count(node_cpu_seconds_total{instance=\"s-shark\"}) by (cpu)))",
     "legendFormat": "s-shark"
    },
    {
     "expr": "1 - sum(irate(node_cpu_seconds_total{instance=\"s-hawk\",mode=\"idle\"}[1m15s])) / scalar(count(count(node_cpu_seconds_total{instance=\"s-hawk\"}) by (cpu)))",
     "legendFormat": "s-hawk"
    },
    {
     "expr": "1 - sum(irate(node_cpu_seconds_total{instance=\"s-snake\",mode=\"idle\"}[1m15s])) / scalar(count(count(node_cpu_seconds_total{instance=\"s-snake\"}) by (cpu)))",
     "legendFormat": "s-snake"
    }
   ]
  },
  { "title": "Argo CD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Applications",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(argocd_app_info) by (project)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(argocd_app_info{sync_status=\"Unknown\"}) by (sync_status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(argocd_app_info{sync_status=\"OutOfSync\"}) by (sync_status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(argocd_app_info{sync_status=\"Synced\"}) by (sync_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum(argocd_app_info{health_status=\"Unknown\"}) by (health_status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(argocd_app_info{health_status=\"Progressing\"}) by (health_status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(argocd_app_info{health_status=\"Suspended\"}) by (health_status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(argocd_app_info{health_status=\"Degraded\"}) by (health_status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(argocd_app_info{health_status=\"Missing\"}) by (health_status)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(argocd_app_info{health_status=\"Healthy\"}) by (health_status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}