apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-api
  namespace: argocd
spec:
  destination:
    namespace: capi-system
    server: https://kubernetes.default.svc
  project: system
  source:
    path: ./manifests/seraphim/prod/cluster-api
    repoURL: https://github.com/scareyo/homelab.git
    targetRevision: main
  syncPolicy: {}
