apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenant-test
  namespace: argocd
spec:
  destination:
    namespace: tenant-test
    server: https://kubernetes.default.svc
  project: system
  source:
    path: ./manifests/seraphim/prod/tenant-test
    repoURL: https://github.com/scareyo/homelab.git
    targetRevision: main
  syncPolicy: {}
