apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
  namespace: argocd
spec:
  destination:
    namespace: kubevirt-hyperconverged
    server: https://kubernetes.default.svc
  project: system
  source:
    path: ./manifests/seraphim/prod/kubevirt
    repoURL: https://github.com/scareyo/homelab.git
    targetRevision: main
  syncPolicy: {}
