apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pocket-id
  namespace: argocd
spec:
  destination:
    namespace: pocket-id
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/seraphim/prod/pocket-id
    repoURL: https://github.com/scareyo/homelab.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
