---
- name: Setup firezone VPN certificates
  hosts: vpn
  remote_user: cloud-user
  become: true
  tasks:
    - name: Request firezone certificate
      ansible.builtin.include_role:
        name: linux-system-roles.certificate
      vars:
        certificate_requests:
          - name: vpn
            dns: vpn.int.scarey.me
            principal: HTTP/vpn.int.scarey.me@INT.SCAREY.ME
            ca: ipa

- name: Setup firezone VPN
  hosts: vpn
  remote_user: cloud-user
  vars:
    firezone_ssl_crt: /etc/pki/tls/certs/vpn.crt
    firezone_ssl_key: /etc/pki/tls/private/vpn.key
  roles:
    - firezone
  tags: vpn
