world:
  config: '{ "daysPerMonth": 30 }'

controllers:
  main:
    initContainers:
      mods:
        enabled: true
        env:
          MODS: "https://mods.vintagestory.at/download/25132/VintageRCon-1.0.zip,https://mods.vintagestory.at/download/29211/OfflineFoodNoSpoil_1.4.0-1.20.zip"
service:
  main:
    annotations:
      io.cilium/lb-ipam-ips: 10.10.21.51
    type: LoadBalancer
    ports:
      rcon:
        port: 42425
        protocol: TCP

configMaps:
  rcon-config:
    data:
      vsrcon.json: |
        {
          "Port": 42425,
          "IP": null,
          "Password": "teddy",
          "Timeout": 20
        }

persistence:
  rcon:
    enabled: true
    name: vintagestory-rcon-config
    type: configMap
    globalMounts:
      - path: /vintagestory/data/ModConfig/vsrcon.json
        subPath: vsrcon.json
