---
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: restore-authentik
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  scheduleName: authentik
  restorePVs: true
  includedResources:
    - pvc
