---
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: default
  namespace: kube-system
spec:
  bgpInstances:
    - name: default
      localASN: 65001
      peers:
        - name: stella
          peerASN: 65000
          peerAddress: "10.10.20.1"
          peerConfigRef:
            name: "default"
