---
- name: Check mandatory variables are defined
  ansible.builtin.assert:
    that:
      - pangolin_email is defined
      - pangolin_password is defined
      - pangolin_secret
      - pangolin_domain is defined

- name: Install Podman
  package:
    name: podman
    state: present

- name: Create Pangolin directory
  ansible.builtin.file:
    path: "/opt/pangolin/config/traefik"
    state: directory
    mode: "0755"

- name: Create Let's Encrypt directory
  ansible.builtin.file:
    path: "/opt/pangolin/config/letsencrypt"
    state: directory
    mode: "0755"

- name: Generate Pangolin config
  ansible.builtin.template:
    src: config.yml.j2
    dest: /opt/pangolin/config/config.yml
    mode: "0644"

- name: Generate Traefik config
  ansible.builtin.template:
    src: traefik_config.yml.j2
    dest: /opt/pangolin/config/traefik/traefik_config.yml
    mode: "0644"

- name: Generate Traefik config
  ansible.builtin.template:
    src: dynamic_config.yml.j2
    dest: /opt/pangolin/config/traefik/dynamic_config.yml
    mode: "0644"

- name: Define containers
  ansible.builtin.include_tasks: "./containers.yaml"
