---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: internal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  gatewayClassName: internal
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: 10.10.21.11
  listeners:
    - protocol: HTTPS
      port: 443
      name: apps-vegapunk-cloud-https
      hostname: "*.vegapunk.cloud"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: apps-vegapunk-cloud-tls
