---
- name: Ensure requirements in place
  ansible.builtin.package:
    name:
      - java-17-openjdk-headless
    state: present

- name: Request Keycloak certificate
  ansible.builtin.include_role:
    name: linux-system-roles.certificate
  vars:
    certificate_requests:
      - name: sso
        dns: sso.int.scarey.me
        principal: HTTP/sso.int.scarey.me@INT.SCAREY.ME
        ca: ipa

- name: Change sso.key ownership
  ansible.builtin.file:
    path: /etc/pki/tls/private/sso.key
    owner: "{{ keycloak_quarkus_service_user }}"
    group: "{{ keycloak_quarkus_service_group }}"

- name: Change sso.crt ownership
  ansible.builtin.file:
    path: /etc/pki/tls/certs/sso.crt
    owner: "{{ keycloak_quarkus_service_user }}"
    group: "{{ keycloak_quarkus_service_group }}"

- name: Redirect port 443 to 8443
  ansible.posix.firewalld:
    rich_rule: rule family=ipv4 forward-port port=443 protocol=tcp to-port=8443
    zone: public
    permanent: true
    immediate: true
    state: enabled

# TODO:
# Role doesn't currently support hostname-url option. I need this to run
# without a proxy.
# hostname-url=https://sso.int.scarey.me"
#
# To workaroud this, I will overwrite the keycloak systemd service
#
# For a more permanent solution I should open a PR to add the option:
#  https://github.com/ansible-middleware/keycloak
#
#  Or maybe I'll just configure a proxy
#

- name: Modify service
  community.general.ini_file:
    path: /etc/systemd/system/keycloak.service
    section: Service
    option: ExecStart
    value: "{{ keycloak.home }}/bin/kc.sh start --auto-build --log={{ keycloak_quarkus_log }} --hostname='' --hostname-url='https://sso.int.scarey.me'"

- name: Restart Keycloak
  ansible.builtin.systemd:
    state: restarted
    name: keycloak
    daemon_reload: true

- name: Add FreeIPA user federation
  ansible.builtin.include_tasks: add_freeipa.yaml
