---
- name: Become true
  become: true
  block:
    - name: Ensure requirements in place
      ansible.builtin.package:
        name:
          - java-17-openjdk-headless
        state: present

    - name: Check if sso certificate exists
      ansible.builtin.stat:
        path: /etc/pki/tls/certs/sso.crt
      register: cert_result

    - name: Check if sso key exists
      ansible.builtin.stat:
        path: /etc/pki/tls/private/sso.key
      register: key_result

    - name: Request Keycloak certificate
      ansible.builtin.include_role:
        name: linux-system-roles.certificate
      vars:
        certificate_requests:
          - name: sso
            dns: sso.int.scarey.me
            principal: HTTP/sso.int.scarey.me@INT.SCAREY.ME
            ca: ipa
      when: not cert_result.stat.exists or not key_result.stat.exists

    - name: Add the user www-data
      ansible.builtin.user:
        name: www-data

    - name: Set sso.key ownership
      ansible.builtin.file:
        path: /etc/pki/tls/private/sso.key
        owner: "www-data"
        group: "www-data"

    - name: Set sso.crt ownership
      ansible.builtin.file:
        path: /etc/pki/tls/certs/sso.crt
        owner: "www-data"
        group: "www-data"

    - name: Setup Caddy
      ansible.builtin.include_role:
        name: caddy_ansible.caddy_ansible
      vars:
        caddy_systemd_capabilities_enabled: true
        caddy_config: |
          sso.int.scarey.me
          tls /etc/pki/tls/certs/sso.crt /etc/pki/tls/private/sso.key
          reverse_proxy http://localhost:8080

- name: Keycloak Quarkus
  ansible.builtin.include_role:
    name: middleware_automation.keycloak.keycloak_quarkus
  vars:
    keycloak_quarkus_jvm_package: java-17-openjdk-headless

- name: Add FreeIPA user federation
  ansible.builtin.include_tasks: add_freeipa.yaml
