---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backblaze-secret
  namespace: velero
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: backblaze-access-key
  data:
    - secretKey: key
      remoteRef:
        key: BACKBLAZE_ACCESS_KEY
