---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: authentik-externalsecret
  data:
    - secretKey: secret_key
      remoteRef:
        key: /authentik/SECRET_KEY
    - secretKey: backblaze_key_id
      remoteRef:
        key: /authentik/BACKBLAZE_KEY_ID
    - secretKey: backblaze_key_secret
      remoteRef:
        key: /authentik/BACKBLAZE_KEY_SECRET
