---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - postgres-cluster.yaml
  - authentik-database.yaml
  - authentik-externalsecret.yaml
  - authentik-httproute.yaml
  - authentik-backup.yaml
  - authentik-restore.yaml
