keys:
  - &scarey 733CC027A4F7D7D74B291D205B0D9896CB89E8D8
  - &newt age1mu0ckyl39qj2xuyfwttze6c0jll6ucr56xtqyrehj6zrn87jkq9sd8zwtt
creation_rules:
  - path_regex: sops/newt.json
    pgp: *scarey
    age: *newt
