---
collections:
  - name: freeipa.ansible_freeipa
  - name: middleware_automation.keycloak

roles:
  - name: geerlingguy.nfs
  - name: githubixx.ansible_role_wireguard
  - name: linux-system-roles.certificate
