---
configs:
  cm:
    url: "https://argocd.apps.int.scarey.me"
    oidc.config: |
      name: Keycloak
      issuer: https://sso.scarey.me/realms/external
      clientID: argocd
      clientSecret: $oidc.keycloak.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
    resource.exclusions: |
      - apiGroups:
        - "velero.io"
        kinds:
        - Backup
        clusters:
        - "*"
    accounts.readonly: apiKey
  rbac:
    policy.csv: |
      g, argocd_admin, role:admin
      g, readonly, role:readonly
  params:
    server.insecure: true
global:
  addPrometheusAnnotations: true
applicationSet:
  metrics:
    enabled: true
controller:
  metrics:
    enabled: true
dex:
  metrics:
    enabled: true
notifications:
  metrics:
    enabled: true
repoServer:
  metrics:
    enabled: true
server:
  metrics:
    enabled: true
