---
- name: Get list of VMs
  community.libvirt.virt:
    command: list_vms
  register: libvirt

- name: Refresh libvirt storage pool
  community.libvirt.virt_pool:
    command: refresh
    name: "{{ vm_storage_pool.name }}"

- name: Get list of storage pools
  community.libvirt.virt_pool:
    command: facts

- name: Create the VM
  vars:
    image_path: "{{ ansible_libvirt_pools[vm_storage_pool.name].path }}"
    image_file: "{{ item.name }}.qcow2"
  when:
    - ansible_libvirt_pools[vm_storage_pool.name] is defined
    - item.name not in libvirt.list_vms
  block:
    - name: Check if the base image already exists
      ansible.builtin.stat:
        path: "{{ image_path }}/{{ vm_base_image_name }}"
      register: stat_result

    - name: Download base image
      ansible.builtin.get_url:
        url: "{{ vm_base_image_url }}"
        dest: "{{ image_path }}/{{ vm_base_image_name }}"
        checksum: "sha256:{{ vm_base_image_sha }}"
        mode: '0644'
      when:
        - vm_base_image_url is defined
        - not stat_result.stat.exists

    - name: Create the VM image
      ansible.builtin.command: |
        qemu-img create -b {{ image_path }}/{{ vm_base_image_name }} -f qcow2 -F qcow2 {{ image_path }}/{{ image_file }} 32G
      register: command_output
      changed_when: command_output.rc != 0
      when: image_file not in ansible_libvirt_pools[vm_storage_pool.name].volumes

    - name: Copy cloud-init user data to host
      ansible.builtin.template:
        src: cloud-init/user-data.yaml.j2
        dest: /tmp/user-data.yaml
        owner: qemu
        group: qemu
        mode: '0644'

    - name: Install the VM
      ansible.builtin.command: |
        virt-install \
          --name "{{ item.name }}" \
          --memory "{{ item.memory }}" \
          --vcpus "{{ item.vcpus }}" \
          --import \
          --cloud-init "user-data='/tmp/user-data.yaml'" \
          --os-variant "{{ vm_os }}" \
          --disk "{{ image_path }}/{{ image_file }}" \
          --network bridge=br0,model=virtio,{% if item.mac_address is defined %}mac={{ item.mac_address }}{% endif %} \
          --graphics vnc \
          --virt-type kvm \
          {% if item.pci_devices is defined %}
            {% for dev in item.pci_devices %}
              --hostdev {{ dev }} \
            {% endfor %}
          {% endif %}
          --noautoconsole \
          --autostart
      register: command_output
      changed_when: command_output.rc != 0
