apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/instance: kamaji
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kamaji
    app.kubernetes.io/version: latest
    helm.sh/chart: kamaji-0.0.0_latest
  name: kamaji-serving-cert
  namespace: kamaji-system
spec:
  dnsNames:
    - kamaji-webhook-service.kamaji-system.svc
    - kamaji-webhook-service.kamaji-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: kamaji-selfsigned-issuer
  secretName: kamaji-webhook-server-cert
