---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: general
  namespace: flux-system
spec:
  type: Static
  defaultValues:
    apps:
      - name: homepage
        path: apps/general/homepage
        dependsOn: []
