---
- name: Install firezone requirements
  become: true
  block:
    - name: Install Docker
      ansible.builtin.include_role:
        name: geerlingguy.docker
      vars:
        docker_users:
          - cloud-user # TODO: configure this and replace occurences of ansible_ssh_user

    - name: Create caddy certificate directory
      ansible.builtin.file:
        path: /home/cloud-user/firezone/caddy/certificates/local/vpn.int.scarey.me
        state: directory
        owner: cloud-user
        group: cloud-user
        mode: '0755'

    - name: Copy certificate to caddy directory
      ansible.builtin.copy:
        remote_src: true
        src: "{{ firezone_ssl_crt }}"
        dest: /home/cloud-user/firezone/caddy/certificates/local/vpn.int.scarey.me/vpn.int.scarey.me.crt
        owner: root
        group: root
        mode: '0600'
      when: firezone_ssl_crt is defined

    - name: Copy key to caddy directory
      ansible.builtin.copy:
        remote_src: true
        src: "{{ firezone_ssl_key }}"
        dest: /home/cloud-user/firezone/caddy/certificates/local/vpn.int.scarey.me/vpn.int.scarey.me.key
        owner: root
        group: root
        mode: '0600'
      when: firezone_ssl_key is defined

- name: Check if container exists
  community.docker.docker_container_info:
    name: firezone-firezone-1
  register: result

- name: Install firezone
  when: not result.exists
  block:
    - name: Create firezone directory
      ansible.builtin.file:
        path: "/home/{{ ansible_ssh_user }}/firezone"
        state: directory
        mode: '0755'

    - name: Download docker-compose.yml
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/firezone/firezone/master/docker-compose.prod.yml
        dest: "/home/{{ ansible_ssh_user }}/firezone/docker-compose.yml"
        mode: '0660'

    - name: Generate required firezone secrets
      community.docker.docker_container:
        name: gen-env
        image: firezone/firezone
        command: "/bin/sh -c 'bin/gen-env > /tmp/.env'"
        volumes:
          - "/home/{{ ansible_ssh_user }}/firezone:/tmp"

    - name: Set external URL
      community.general.ini_file:
        path: "/home/{{ ansible_ssh_user }}/firezone/.env"
        section: null
        option: EXTERNAL_URL
        value: "https://vpn.int.scarey.me"
        mode: '0600'
        no_extra_spaces: true
        backup: true

    - name: Set admin email
      community.general.ini_file:
        path: "/home/{{ ansible_ssh_user }}/firezone/.env"
        section: null
        option: DEFAULT_ADMIN_EMAIL
        value: "sam@scarey.me"
        mode: '0600'
        no_extra_spaces: true
        backup: true

    - name: Enable custom certificates
      community.general.ini_file:
        path: "/home/{{ ansible_ssh_user }}/firezone/.env"
        section: null
        option: TLS_OPTS
        value: |
          "tls internal {
             on_demand
          }"
        mode: '0600'
        no_extra_spaces: true
        backup: true

    # TODO: Add a check before performing the next 3 docker compose run steps
    - name: Migrate database
      ansible.builtin.command: docker compose run --rm firezone bin/migrate
      register: command_output
      changed_when: command_output.rc != 0
      args:
        chdir: "/home/{{ ansible_ssh_user }}/firezone"

    - name: Create admin account
      ansible.builtin.command: docker compose run --rm firezone bin/create-or-reset-admin
      register: command_output
      changed_when: command_output.rc != 0
      args:
        chdir: "/home/{{ ansible_ssh_user }}/firezone"

    - name: Docker compose up
      ansible.builtin.command: docker compose up -d
      register: command_output
      changed_when: command_output.rc != 0
      args:
        chdir: "/home/{{ ansible_ssh_user }}/firezone"
