---
- block:
  - name: Install Docker
    include_role:
      name: geerlingguy.docker
    vars:
      docker_users:
        - cloud-user # TODO: configure this

  - name: Request firezone certificate
    include_role:
      name: linux-system-roles.certificate
    vars:
      certificate_requests:
        - name: vpn
          dns: vpn.int.scarey.me
          principal: HTTP/vpn.int.scarey.me@INT.SCAREY.ME
          ca: ipa
  become: true

- name: Create firezone directory
  ansible.builtin.file:
    path: "/home/{{ ansible_ssh_user }}/firezone"
    state: directory
    mode: '0755'

- name: Download docker-compose.yml
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/firezone/firezone/master/docker-compose.prod.yml
    dest: "/home/{{ ansible_ssh_user }}/firezone/docker-compose.yml"
    mode: '0660'

- name: Generate required firezone secrets
  docker_container:
    name: gen-env
    image: firezone/firezone
    command: "/bin/sh -c 'bin/gen-env > /tmp/.env'"
    volumes:
      - "/home/{{ ansible_ssh_user }}/firezone:/tmp"

- name: Set external URL
  community.general.ini_file:
    path: "/home/{{ ansible_ssh_user }}/firezone/.env"
    section: null
    option: EXTERNAL_URL
    value: "https://vpn.int.scarey.me"
    mode: '0600'
    no_extra_spaces: true
    backup: true

- name: Set admin email
  community.general.ini_file:
    path: "/home/{{ ansible_ssh_user }}/firezone/.env"
    section: null
    option: DEFAULT_ADMIN_EMAIL
    value: "sam@scarey.me"
    mode: '0600'
    no_extra_spaces: true
    backup: true

- name: Enable custom certificates
  community.general.ini_file:
    path: "/home/{{ ansible_ssh_user }}/firezone/.env"
    section: null
    option: TLS_OPTS
    value: | 
      "tls internal {
         on_demand
       }"
    mode: '0600'
    no_extra_spaces: true
    backup: true

- name: Migrate database
  ansible.builtin.command: docker compose run --rm firezone bin/migrate
  args:
    chdir: "/home/{{ ansible_ssh_user }}/firezone"

- name: Create admin account
  ansible.builtin.command: docker compose run --rm firezone bin/create-or-reset-admin
  args:
    chdir: "/home/{{ ansible_ssh_user }}/firezone"

- name: Docker compose up
  ansible.builtin.command: docker compose up -d
  args:
    chdir: "/home/{{ ansible_ssh_user }}/firezone"
