apiVersion: v1
data:
  ROOK_CEPH_ALLOW_LOOP_DEVICES: "false"
  ROOK_CEPH_COMMANDS_TIMEOUT_SECONDS: "15"
  ROOK_CEPH_MON_RUN_AS_ROOT: "false"
  ROOK_DELETE_UNUSED_CRUSH_RULES: "true"
  ROOK_ENABLE_DISCOVERY_DAEMON: "false"
  ROOK_LOG_LEVEL: INFO
  ROOK_OBC_ALLOW_ADDITIONAL_CONFIG_FIELDS: maxObjects,maxSize
  ROOK_OBC_WATCH_OPERATOR_NAMESPACE: "true"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/created-by: helm
    app.kubernetes.io/instance: rook-ceph
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: rook-ceph
    app.kubernetes.io/part-of: rook-ceph-operator
    app.kubernetes.io/version: v1.20.8
    helm.sh/chart: rook-ceph-v1.20.8
    operator: rook
    storage-backend: ceph
  name: rook-ceph-operator-config
  namespace: rook-ceph
