- name: Gather facts about storage pools
  community.libvirt.virt_pool:
    command: facts

- debug:
    var: ansible_libvirt_pools

- name: Create the local storage pool 
  import_tasks: create_local_storage_pool.yaml
  when: ansible_libvirt_pools["local"] is not defined

- name: Provision the NAS VM
  import_tasks: create_local_storage_pool.yaml
