apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: config
  namespace: immich
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /immich/OIDC_CLIENT_ID
        metadataPolicy: None
      secretKey: key
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /immich/OIDC_CLIENT_SECRET
        metadataPolicy: None
      secretKey: secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    template:
      data:
        immich-config.yaml: |
          oauth:
            enabled: true
            clientId: "{{ .key }}"
            clientSecret: "{{ .secret }}"
            issuerUrl: "https://id.vegapunk.cloud"
          passwordLogin:
            enabled: false
      engineVersion: v2
