apiVersion: v1
data:
  oauth2_proxy.cfg: |
    upstreams="http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
    email_domains="*"
    redirect_url="https://prometheus.vegapunk.cloud/oauth2/callback"
    provider="oidc"
    scope="openid email profile groups"
    oidc_issuer_url="https://id.vegapunk.cloud"
    provider_display_name="Prometheus"
    custom_sign_in_logo="https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/prometheus.svg"
    banner="Prometheus"
    insecure_oidc_allow_unverified_email="true"
kind: ConfigMap
metadata:
  labels:
    app: oauth2-proxy
    app.kubernetes.io/component: authentication-proxy
    app.kubernetes.io/instance: oauth2-proxy-prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/part-of: oauth2-proxy
    app.kubernetes.io/version: 7.13.0
    helm.sh/chart: oauth2-proxy-9.0.0
  name: oauth2-proxy-prometheus
  namespace: monitoring
