---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: apps
spec:
  type: Static
  defaultValues:
    apps:
      # Forgejo
      - name: app-forgejo
        path: k8s/apps/forgejo

      # Prowlarr
      - name: app-prowlarr
        path: k8s/apps/prowlarr

      # Sonarr
      - name: app-sonarr
        path: k8s/apps/sonarr
