---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: infrastructure
spec:
  type: Static
  defaultValues:
    apps:
      # Cilium
      - name: infra-cilium
        path: k8s/infrastructure/cilium
        timeout: []
        dependsOn: []
        healthChecks: []
        healthCheckExprs: []

      - name: infra-cilium-config
        path: k8s/infrastructure/cilium/config
        timeout: []
        dependsOn:
          - infra-cilium
        healthChecks: []
        healthCheckExprs: []

      # Flux Operator
      - name: infra-fluxcd
        path: k8s/infrastructure/fluxcd
        timeout: []
        dependsOn: []
        healthChecks: []
        healthCheckExprs: []

      - name: infra-fluxcd-config
        path: k8s/infrastructure/fluxcd/config
        timeout: []
        dependsOn: []
        healthChecks: []
        healthCheckExprs: []

      ## External Secrets
      - name: infra-external-secrets
        path: k8s/infrastructure/external-secrets
        timeout: []
        dependsOn: []
        healthChecks: []
        healthCheckExprs: []

      - name: infra-external-secrets-config
        path: k8s/infrastructure/external-secrets/config
        timeout: []
        dependsOn:
          - infra-external-secrets
        healthChecks: []
        healthCheckExprs:
          - apiVersion: external-secrets.io/v1beta1
            kind: ClusterSecretStore
            failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
            current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')

      # Hetzner Cloud
      - name: infra-hcloud
        path: k8s/infrastructure/hcloud
        timeout: []
        dependsOn:
          - infra-external-secrets-config
        healthChecks: []
        healthCheckExprs: []

      ## cert-manager
      - name: infra-cert-manager
        path: k8s/infrastructure/cert-manager
        timeout: []
        dependsOn:
          - infra-external-secrets-config
        healthChecks: []
        healthCheckExprs: []

      - name: infra-cert-manager-config
        path: k8s/infrastructure/cert-manager/config
        timeout: []
        dependsOn:
          - infra-cert-manager
        healthChecks: []
        healthCheckExprs:
          - apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
            current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')

      # Gateway
      - name: infra-gateway
        path: k8s/infrastructure/gateway
        timeout: []
        dependsOn:
          - infra-cert-manager-config
        healthChecks: []
        healthCheckExprs: []

      # External DNS
      - name: infra-external-dns
        path: k8s/infrastructure/external-dns
        timeout: []
        dependsOn:
          - infra-external-secrets-config
          - infra-gateway
        healthChecks: []
        healthCheckExprs: []

      # External Snapshotter
      - name: infra-external-snapshotter
        path: k8s/infrastructure/external-snapshotter
        timeout: []
        dependsOn: []
        healthChecks: []
        healthCheckExprs: []

      ## Rook
      - name: infra-rook
        path: k8s/infrastructure/rook
        timeout: 15m
        dependsOn:
          - infra-gateway
        healthChecks:
          - apiVersion: helm.toolkit.fluxcd.io/v2
            kind: HelmRelease
            name: rook-ceph-cluster
            namespace: rook-ceph
          - apiVersion: ceph.rook.io/v1
            kind: CephCluster
            name: rook-ceph
            namespace: rook-ceph
        healthCheckExprs:
          - apiVersion: ceph.rook.io/v1
            kind: CephCluster
            failed: status.conditions.exists(e, e.status == 'False')
            current: status.conditions.exists(e, e.type == 'Ready' && e.status == 'True')

      ## Velero
      - name: infra-velero
        path: k8s/infrastructure/velero
        timeout: []
        dependsOn:
          - infra-external-secrets-config
        healthChecks: []
        healthCheckExprs: []

      - name: infra-velero-schedules
        path: k8s/infrastructure/velero/schedules
        timeout: []
        dependsOn:
          - infra-velero
          - infra-rook
        healthChecks: []
        healthCheckExprs: []

      - name: infra-velero-restores
        path: k8s/infrastructure/velero/restores
        timeout: []
        dependsOn:
          - infra-velero-schedules
        healthChecks: []
        healthCheckExprs: []

      # CloudNativePG
      - name: infra-cnpg
        path: k8s/infrastructure/cnpg
        timeout: []
        dependsOn:
          - infra-rook
        healthChecks: []
        healthCheckExprs: []

      # Pocket ID
      - name: infra-pocket-id
        path: k8s/infrastructure/pocket-id
        timeout: []
        dependsOn:
          - infra-cnpg
          - infra-velero-restores
        healthChecks: []
        healthCheckExprs: []
