---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: seraphim
  namespace: flux-system
spec:
  inputsFrom:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSetInputProvider
      name: infrastructure

  resourcesTemplate: |
    <<- range $app := inputs.apps >>
    ---
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: << $app.name >>
      namespace: flux-system
    spec:
      << if $app.dependsOn >>
      dependsOn:
        <<- range $dep := $app.dependsOn >>
        - name: << $dep >>
        <<- end >>
      << end >>
      path: << $app.path >>
      interval: 30m
      retryInterval: 5m
      prune: true
      << if $app.healthChecks >>
      wait: false
      healthChecks:
        <<- range $check := $app.healthChecks >>
        - apiVersion: << $check.apiVersion >>
          kind: << $check.kind >>
          name: << $check.name >>
          namespace: << $check.namespace >>
        <<- end >>
      << else >>
      wait: true
      << end >>
      << if $app.healthCheckExprs >>
      healthCheckExprs:
        <<- range $expr := $app.healthCheckExprs >>
        - apiVersion: << $expr.apiVersion >>
          kind: << $expr.kind >>
          failed: << $expr.failed >>
          current: << $expr.current >>
        <<- end >>
      << end >>
      << if $app.timeout >>
      timeout: << $app.timeout >>
      << else >>
      timeout: 5m
      << end >>
      sourceRef:
        kind: GitRepository
        name: flux-system
    <<- end >>
