apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  data:
    - remoteRef:
        key: /cloudflare/API_TOKEN
      secretKey: token
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudflare-api-token
