---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: system
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.7.13
      helm:
        valueFiles:
          - $repo/seraphim/system/argocd/values.yaml
    - repoURL: https://github.com/scareyo/homelab.git
      targetRevision: develop
      path: seraphim/system/argocd
      ref: repo
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
