---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: system
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.16.2
      helm:
        valueFiles:
          - $repo/seraphim/system/cert-manager/values.yaml
    - repoURL: https://github.com/scareyo/homelab.git
      targetRevision: develop
      path: seraphim/system/cert-manager
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
