---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: system
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io
      targetRevision: 0.13.0
    - repoURL: https://github.com/scareyo/homelab.git
      targetRevision: main
      path: seraphim/system/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
