---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: system
  sources:
    - chart: velero
      repoURL: "https://vmware-tanzu.github.io/helm-charts"
      targetRevision: 8.3.0
      helm:
        valueFiles:
          - $repo/seraphim/system/velero/values.yaml
    - repoURL: "https://github.com/scareyo/homelab.git"
      targetRevision: develop
      path: "seraphim/system/velero"
      ref: repo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
