apiVersion: v1
data:
  ANALYTICS_DISABLED: "false"
  APP_URL: https://id.vegapunk.cloud
  AUDIT_LOG_RETENTION_DAYS: "90"
  DISABLE_RATE_LIMITING: "false"
  FILE_BACKEND: filesystem
  GEOLITE_DB_PATH: data/GeoLite2-City.mmdb
  GEOLITE_DB_URL: https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=%s&suffix=tar.gz
  HOST: 0.0.0.0
  INTERNAL_APP_URL: ""
  LOCAL_IPV6_RANGES: ""
  LOG_JSON: "false"
  LOG_LEVEL: info
  METRICS_ENABLED: "false"
  PORT: "1411"
  TRACING_ENABLED: "false"
  TRUST_PROXY: "true"
  TZ: America/New_York
  UI_CONFIG_DISABLED: "false"
  UPLOAD_PATH: data/uploads
  VERSION_CHECK_DISABLED: "true"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: pocket-id
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pocket-id
    helm.sh/chart: pocket-id-2.0.3
  name: pocket-id
  namespace: pocket-id
