---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anubis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: anubis
  data:
    - secretKey: ED25519_PRIVATE_KEY_HEX
      remoteRef:
        key: /forgejo/ANUBIS_ED25519_PRIVATE_KEY_HEX

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anubis
  labels:
    app: anubis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anubis
  template:
    metadata:
      labels:
        app: anubis
    spec:
      containers:
        - name: anubis
          image: ghcr.io/techarohq/anubis:latest
          imagePullPolicy: Always
          env:
            - name: BIND
              value: :8080
            - name: DIFFICULTY
              value: "4"
            - name: ED25519_PRIVATE_KEY_HEX
              valueFrom:
                secretKeyRef:
                  name: anubis
                  key: ED25519_PRIVATE_KEY_HEX
            - name: METRICS_BIND
              value: :9090
            - name: SERVE_ROBOTS_TXT
              value: "true"
            - name: TARGET
              value: http://forgejo-http:3000
            - name: OG_PASSTHROUGH
              value: "true"
            - name: OG_EXPIRY_TIME
              value: 24h
            - name: USE_REMOTE_ADDRESS
              value: "true"
          resources:
            limits:
              cpu: 750m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 256Mi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault

---
apiVersion: v1
kind: Service
metadata:
  name: anubis
spec:
  selector:
    app: anubis
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: anubis
