---
name: forgejo
namespace: forgejo
sources:
  - type: helm
    chart: forgejo
    repoURL: code.forgejo.org/forgejo-helm
    targetRevision: 13.0.1

  - type: dir
    path: config

ignoreDifferences:
  - group: ''
    kind: Secret
    name: forgejo-postgresql-ha-pgpool
    jsonPointers:
      - /data/sr-check-password
