---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: oidc
  data:
    - secretKey: key
      remoteRef:
        key: /forgejo/OIDC_CLIENT_ID
    - secretKey: secret
      remoteRef:
        key: /forgejo/OIDC_CLIENT_SECRET
