---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  chart:
    spec:
      chart: forgejo
      version: 14.0.3
      sourceRef:
        kind: HelmRepository
        name: forgejo
  releaseName: forgejo
  interval: 10m
  values:
    gitea:
      config:
        server:
          ROOT_URL: https://git.scarey.me
        service:
          DISABLE_REGISTRATION: true
        oauth2_client:
          ENABLE_AUTO_REGISTRATION: true
          UPDATE_AVATAR: true
        database:
          DB_TYPE: postgres
      additionalConfigFromEnvs:
        - name: FORGEJO__DATABASE__HOST
          valueFrom:
            secretKeyRef:
              name: postgres-app
              key: host
        - name: FORGEJO__DATABASE__NAME
          valueFrom:
            secretKeyRef:
              name: postgres-app
              key: dbname
        - name: FORGEJO__DATABASE__USER
          valueFrom:
            secretKeyRef:
              name: postgres-app
              key: username
        - name: FORGEJO__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: postgres-app
              key: password
      oauth:
        - name: pocket-id
          provider: openidConnect
          existingSecret: oidc
          autoDiscoverUrl: https://id.scarey.me/.well-known/openid-configuration
          iconUrl: https://id.scarey.me/api/application-configuration/logo
          scopes: email profile groups
          groupClaimName: groups
          adminGroup: forgejo_admin
          restrictedGroup: forgejo_restricted
