---
name: longhorn
namespace: longhorn-system
enforce: privileged
sources:
  - type: helm
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.9.1

  - type: dir
    path: config
