---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  data:
    - secretKey: token
      remoteRef:
        key: /hcloud/API_TOKEN
