---
- name: Create MetalLB L2Advertisement
  kubernetes.core.k8s:
    state: present
    src: "{{ cozystack_config_dir }}/config/metallb/cozystack-l2advertisement.yaml"
  run_once: true

- name: Create MetalLB IPAddressPool
  kubernetes.core.k8s:
    state: present
    src: "{{ cozystack_config_dir }}/config/metallb/cozystack-ipaddresspool.yaml"
  run_once: true

- name: Enable root ingress
  kubernetes.core.k8s:
    state: patched
    name: root
    namespace: tenant-root
    api_version: apps.cozystack.io/v1alpha1
    kind: Tenant
    definition:
      spec:
        ingress: true
  run_once: true

- name: Wait for ingress
  kubernetes.core.k8s_info:
    name: ingress
    namespace: tenant-root
    api_version: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    wait: true
    wait_condition:
      type: Ready
    wait_timeout: 60
  run_once: true

- name: Wait for ingress-nginx-system
  kubernetes.core.k8s_info:
    name: ingress-nginx-system
    namespace: tenant-root
    api_version: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    wait: true
    wait_condition:
      type: Ready
    wait_timeout: 60
  run_once: true
