---
- name: Ensure requirements in place
  package:
    name:
      - python3-libvirt
    state: present
  become: yes

- name: New storage pool
  include_tasks: new_pool.yaml
  loop: "{{ pools }}"
  when: command == "new-pool"

- name: New virtual machine
  include_tasks: new_vm.yaml
  loop: "{{ vms }}"
  when: command == "new-vm"
