---
- name: Gather facts about storage pools
  community.libvirt.virt_pool:
    command: facts

- name: New storage pool
  include_tasks: new_pool.yaml
  vars:
    pools: "{{ pools }}"
  when: 
    - command == "new-pool"
    - ansible_libvirt_pools["local"] is not defined

- name: New virtual machine
  include_tasks: new_vm.yaml
  loop: "{{ vms }}"
  when: command == "new-vm"
