---
- name: Ensure requirements in place
  ansible.builtin.package:
    name:
      - python3-libvirt
    state: present
  become: true

- name: New storage pool
  ansible.builtin.include_tasks: new_pool.yaml
  loop: "{{ libvirt_pools }}"
  when: command == "new-pool"

- name: New virtual machine
  ansible.builtin.include_tasks: new_vm.yaml
  loop: "{{ libvirt_vms }}"
  when: command == "new-vm"
