---
- name: Get list of VMs
  community.libvirt.virt:
    command: list_vms
  register: vm_list
  changed_when: no

- name: Refresh libvirt storage pool
  community.libvirt.virt_pool:
    command: refresh
    name: "{{ item.pool }}"

- name: Get list of storage pools
  community.libvirt.virt_pool:
    command: facts

- vars:
    image_path: "{{ ansible_libvirt_pools[item.pool].path }}"
    image_file: "{{ item.name }}.qcow2"
  block:
    - name: Download base image
      get_url:
        url: "{{ base_image_url }}"
        dest: "{{ image_path }}/{{ base_image_name }}"
        checksum: "sha256:{{ base_image_sha }}"

    - name: Create the VM image
      command: |
        qemu-img create -b {{ image_path }}/{{ base_image_name }} -f qcow2 -F qcow2 {{ image_path }}/{{ image_file }} 32G
      when: image_file not in ansible_libvirt_pools[item.pool].volumes

    - name: Copy cloud-init user data to host
      ansible.builtin.template:
        src: cloud-init/user-data.yaml.j2
        dest: /tmp/user-data.yaml
        owner: qemu
        group: qemu
        mode: '0644'

    - name: Install the VM
      command: |
        virt-install \
          --name "{{ item.name }}" \
          --memory "{{ item.memory }}" \
          --vcpus "{{ item.vcpus }}" \
          --import \
          --cloud-init "user-data='/tmp/user-data.yaml'" \
          --os-variant almalinux9 \
          --disk "{{ image_path }}/{{ image_file }}" \
          --network bridge=br0,model=virtio,{% if item.mac_address is defined %}mac={{ item.mac_address }}{% endif %} \
          --graphics vnc \
          --virt-type kvm \
          {% for dev in item.pci_devices %}
            --hostdev {{ dev }} \
          {% endfor %}
          --noautoconsole

  when: 
    - ansible_libvirt_pools[item.pool] is defined
    - item.name not in vm_list.list_vms
