---
- name: Gather facts about storage pools
  community.libvirt.virt_pool:
    command: facts

- block:
  - name: Define the storage pool
    community.libvirt.virt_pool:
      command: define
      name: "{{ item.name }}"
      xml: '{{ lookup("template", "storage/pool.xml.j2") }}'

  - name: Create the storage pool
    community.libvirt.virt_pool:
      command: build
      name: "{{ item.name }}"

  - name: Start the storage pool
    community.libvirt.virt_pool:
      command: create
      name: "{{ item.name }}"

  - name: Autostart the storage pool
    community.libvirt.virt_pool:
      autostart: yes
      name: "{{ item.name }}"

  when: ansible_libvirt_pools[item.name] is not defined
