apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: system
  source:
    path: ./manifests/seraphim/cilium
    repoURL: https://github.com/scareyo/homelab
    targetRevision: main
  syncPolicy: {}
