apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao
  namespace: argocd
spec:
  destination:
    namespace: openbao
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/seraphim/openbao
    repoURL: https://knot1.tangled.sh/did:plc:jkfcue6cc7extm56pyw4lgoc
    targetRevision: main
  syncPolicy: {}
