apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: system
  source:
    path: ./manifests/seraphim/external-secrets
    repoURL: https://knot1.tangled.sh/did:plc:jkfcue6cc7extm56pyw4lgoc
    targetRevision: main
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
