apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  destination:
    namespace: openebs
    server: https://kubernetes.default.svc
  project: system
  source:
    path: ./manifests/seraphim/openebs
    repoURL: https://github.com/scareyo/homelab
    targetRevision: main
  syncPolicy: {}
