---
talos_version: 1.11.1
kubernetes_version: 1.33.0

omni_cluster_name: seraphim

omni_endpoint: "{{ lookup('secret', '/omni', 'ENDPOINT') }}"
omni_service_account_key: "{{ lookup('secret', '/omni', 'SERVICE_ACCOUNT_KEY') }}"

infisical_client_id: "{{ lookup('secret', '/infisical', 'SERAPHIM_CLIENT_ID') }}"
infisical_client_secret: "{{ lookup('secret', '/infisical', 'SERAPHIM_CLIENT_SECRET') }}"
