---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
spec:
  project: system
  source:
    repoURL: "https://github.com/scareyo/homelab.git"
    targetRevision: develop
    path: "seraphim/system/cilium"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
