---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
spec:
  project: system
  source:
    repoURL: "https://github.com/scareyo/homelab.git"
    targetRevision: develop
    path: "seraphim/system/cnpg"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
