---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: "https://github.com/scareyo/homelab.git"
        revision: develop
        directories:
          - path: seraphim/system/*
          - path: seraphim/system/cilium
            exclude: true
          - path: seraphim/system/rook
            exclude: true
          - path: seraphim/system/cnpg
            exclude: true
  template:
    metadata:
      name: "{{`{{.path.basename}}`}}"
    spec:
      project: "system"
      source:
        repoURL: "https://github.com/scareyo/homelab.git"
        targetRevision: develop
        path: "{{`{{.path.path}}`}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{`{{.path.basename}}`}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
