---
projects:
  - name: infrastructure
    steps:
      - base
      - cilium
      - cnpg
      - external-secrets
      - hcloud
      - cert-manager
      - gateway
      - external-dns
      - external-snapshotter
      - rook
      - velero
      - argocd
      - authentik

  - name: apps
