---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate
  namespace: renovate
data:
  RENOVATE_ALLOWED_POST_UPGRADE_COMMANDS: "nix run --extra-experimental-features nix-command --extra-experimental-features flakes .#"
  RENOVATE_AUTODISCOVER: "false"
  RENOVATE_GIT_AUTHOR: "Renovate Bot <bot@renovateapp.com>"
  RENOVATE_PLATFORM: "github"
