---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: cloudflare-api-token
  data:
    - secretKey: token
      remoteRef:
        key: 9dbbf5b3-d1f0-4bc8-b0a5-b26b016dd3c3
