---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            namespace: cozy-external-secrets-operator
            name: infisical-credentials
          clientSecret:
            key: clientSecret
            namespace: cozy-external-secrets-operator
            name: infisical-credentials
      secretsScope:
        projectSlug: homelab
        environmentSlug: prod
