---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backblaze
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: backblaze-externalsecret
  data:
    - secretKey: key
      remoteRef:
        key: /velero/BACKBLAZE_KEY
