endpoint: https://api.vegapunk.cloud:6443
clusterDomain: vegapunk.local
image: ghcr.io/cozystack/cozystack/talos:v1.10.6
podSubnets:
  - 10.244.0.0/16
serviceSubnets:
  - 10.96.0.0/16
advertisedSubnets:
  - 10.10.20.0/24
oidcIssuerUrl: "https://keycloak.vegapunk.cloud/realms/cozy"
certSANs: []
nr_hugepages: 0

installDisk: SAMSUNG MZQLB960HAJR-00007
