---
apiVersion: velero.io/v1
kind: Restore
metadata:
  generateName: restore-
  namespace: velero
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backupName: gateway
  includedResources:
    - secrets
