---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
  namespace: external-secrets
spec:
  provider:
    bitwardensecretsmanager:
      organizationID: dc6a0216-47c4-46aa-9a16-aa3c00ef5b84
      projectID: f22bd8f8-1b60-453b-9818-b01e0010c6d0
      auth:
        secretRef:
          credentials:
            namespace: external-secrets
            name: bws-access-token
            key: token
