---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: "default"
  source:
    repoURL: "https://github.com/scareyo/homelab.git"
    targetRevision: develop-talos
    path: 'apps/metallb'
  destination:
    server: https://kubernetes.default.svc
    namespace: 'metallb'
  syncPolicy:
    automated:
      prune: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    syncOptions:
      - CreateNamespace=true
