apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  data:
    - remoteRef:
        key: cloudflare
        property: api-token
      secretKey: api-token
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target: {}
