---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: forgejo-daily
  namespace: velero
spec:
  schedule: 0 4 * * *
  template:
    ttl: 168h0m0s # 1 week
    includedNamespaces:
      - forgejo
    includedResources:
      - pv
      - pvc
    snapshotVolumes: true
    snapshotMoveData: true

---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: forgejo-quarterly
  namespace: velero
spec:
  schedule: 0 0 1 1,4,7,10 *
  template:
    ttl: 8760h0m0s # 1 year
    includedNamespaces:
      - forgejo
    includedResources:
      - pv
      - pvc
    snapshotVolumes: true
    snapshotMoveData: true
