apiVersion: v1
data:
  inifile: |
    [chttpd]
    bind_address = any
    require_valid_user = false

    [couchdb]
    uuid = 063521ad8331413ba49f017072cbd9d1
  seedlistinifile: |
    [cluster]
    seedlist = couchdb@couchdb-couchdb-0.couchdb-couchdb.obsidian.svc.cluster.local,couchdb@couchdb-couchdb-1.couchdb-couchdb.obsidian.svc.cluster.local,couchdb@couchdb-couchdb-2.couchdb-couchdb.obsidian.svc.cluster.local
kind: ConfigMap
metadata:
  labels:
    app: couchdb
    chart: couchdb-4.6.3
    heritage: Helm
    release: couchdb
  name: couchdb-couchdb
  namespace: obsidian
