apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: couchdb
  namespace: obsidian
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /obsidian/ADMIN_USERNAME
        metadataPolicy: None
      secretKey: adminUsername
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /obsidian/ADMIN_PASSWORD
        metadataPolicy: None
      secretKey: adminPassword
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /obsidian/COOKIE_AUTH_SECRET
        metadataPolicy: None
      secretKey: cookieAuthSecret
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /obsidian/ERLANG_COOKIE
        metadataPolicy: None
      secretKey: erlangCookie
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target: {}
