---
name: hcloud
namespace: hcloud
autosync: true
syncWave: "-30"
sources:
  - type: helm
    chart: hcloud-cloud-controller-manager
    repoURL: https://charts.hetzner.cloud
    targetRevision: 1.26.0

  - type: dir
    path: config
