apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets
          serviceAccountRef:
            name: openbao
            namespace: external-secrets
      namespace: seraphim
      path: secret
      server: http://openbao.openbao.svc.cluster.local:8200
      version: v2
