apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/version: v2.3.0
    helm.sh/chart: external-secrets-2.3.0
  name: external-secrets-metrics
  namespace: external-secrets
spec:
  endpoints:
    - honorLabels: false
      interval: 30s
      port: metrics
      scrapeTimeout: 25s
  namespaceSelector:
    matchNames:
      - external-secrets
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/name: external-secrets
