---
- name: Deploy seraphim cluster to metal
  hosts: seraphim
  connection: local
  vars:
    secrets: "{{ lookup('infisical.vault.read_secrets', env_slug='prod', project_id='64853e11f7a9ba1c4ac21cfd', path='/') | items2dict }}"
  roles:
    - role: pxe
      vars:
        pxe_os: "talos"
        pxe_subnet: "10.10.22.0/24"
        pxe_config:
          talos:
            config: "{{ talos_config }}"
            cluster_name: "seraphim"
            cluster_endpoint: "https://seraphim.int.scarey.me:6443"
            osdisk: "{{ osdisk }}"
            secrets: "{{ playbook_dir }}/../../secrets/talos.yaml"
  tasks:
    - name: Set hosts to boot from PXE
      ansible.builtin.command: "amtcli boot pxe {{ amt_host }} --username {{ secrets.AMT_USERNAME }} --password {{ secrets.AMT_PASSWORD }}"
      changed_when: true
      register: cmd
      retries: 5
      until: cmd.rc == 0

    - name: Start hosts
      ansible.builtin.command: "amtcli on {{ amt_host }} --username {{ secrets.AMT_USERNAME }} --password {{ secrets.AMT_PASSWORD }}"
      changed_when: true
      register: cmd
      until: cmd.rc == 0

- name: Bootstrap Talos
  hosts: bootstrap
  connection: local
  tasks:
    - name: Bootstrap cluster
      ansible.builtin.command: "talosctl --nodes {{ talos_host }} --endpoints {{ talos_host }} bootstrap"
      retries: 30
      delay: 10
      changed_when: true

- name: Wait for running nodes
  hosts: seraphim
  connection: local
  tasks:
    - name: Wait for running nodes
      ansible.builtin.command: "talosctl --nodes {{ talos_host }} --endpoints {{ talos_host }} get nodestatus -o json"
      changed_when: false
      retries: 60
      delay: 5
      register: cmd
      until: cmd.stdout != "" and (cmd.stdout | from_json).metadata.phase == "running"

    - name: Wipe storage disk
      ansible.builtin.command: "talosctl --nodes {{ talos_host }} --endpoints {{ talos_host }} wipe disk nvme0n1"
      changed_when: false
