---
- name: Configure seraphim cluster
  hosts: bootstrap
  connection: local
  tasks:
    - name: Generate talosconfig
      ansible.builtin.command: >
        talosctl gen config seraphim https://seraphim.int.scarey.me:6443
          --with-secrets {{ inventory_dir }}/../secrets/talos.yaml
          --output-types talosconfig
          --output {{ inventory_dir }}/../.talos/config
          --force
      changed_when: true

    - name: Download admin kubeconfig
      ansible.builtin.command: >
        talosctl --nodes {{ ansible_host }} --endpoints {{ ansible_host }} kubeconfig {{ inventory_dir }}/../.kube/config --force
      changed_when: true

    - name: Change talosconfig permissions
      ansible.builtin.file:
        path: "{{ inventory_dir }}/../.talos/config"
        mode: '0600'

    - name: Change kubeconfig permissions
      ansible.builtin.file:
        path: "{{ inventory_dir }}/../.kube/config"
        mode: '0600'

- name: Wait for running nodes
  hosts: seraphim
  connection: local
  tasks:
    - name: Wait for running nodes
      ansible.builtin.command: "talosctl --nodes {{ ansible_host }} --endpoints {{ ansible_host }} get nodestatus -o json"
      changed_when: false
      retries: 30
      delay: 5
      register: cmd
      until: cmd.stdout != "" and (cmd.stdout | from_json).metadata.phase == "running"

- name: Deploy initial services
  hosts: bootstrap
  connection: local
  tasks:
    - name: Bootstrap Cilium
      kubernetes.core.k8s:
        definition: "{{ lookup('kubernetes.core.kustomize', dir='{{ inventory_dir }}/../apps/cilium', enable_helm=True) }}"
    
    - name: Wait for healthy cluster
      ansible.builtin.command: "talosctl --nodes {{ ansible_host }} --endpoints {{ ansible_host }} health"
      changed_when: false

    - name: Bootstrap Argo CD
      kubernetes.core.k8s:
        definition: "{{ lookup('kubernetes.core.kustomize', dir='{{ inventory_dir }}/../apps/argocd', enable_helm=True) }}"
