cluster:
  name: seraphim
clusterMetrics:
  enabled: true
clusterEvents:
  enabled: true
podLogs:
  enabled: true
alloy-logs:
  enabled: true
alloy-metrics:
  enabled: true
alloy-singleton:
  enabled: true
destinations:
  - name: prometheus
    type: prometheus
    url: http://prometheus-server.monitoring.svc.cluster.local/api/v1/write
  - name: loki
    type: loki
    url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
