cluster:
  name: seraphim
clusterMetrics:
  enabled: true
  node-exporter:
    metricsTuning:
      useIntegrationAllowList: true
clusterEvents:
  enabled: true
alloy-metrics:
  enabled: true
alloy-singleton:
  enabled: true
destinations:
  - name: prometheus
    type: prometheus
    url: http://prometheus-server.monitoring.svc.cluster.local:9090
  - name: loki
    type: loki
    url: http://loki-gateway.monitoring.svc.cluster.local
