---
- name: Get secrets
  vars:
    id: 64853e11f7a9ba1c4ac21cfd
  ansible.builtin.set_fact:
    "{{ item }}": "{{ [lookup('infisical.vault.read_secrets', project_id=id, env_slug='prod', path='/' + item)] | flatten | items2dict }}"
  loop: "{{ paths }}"
