apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-encryption
  namespace: homarr
spec:
  dataFrom:
    - rewrite:
        - regexp:
            source: password
            target: db-encryption-key
      sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: db-encryption-key
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target: {}
