apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agentgateway-local-role-agentgateway-system
  namespace: agentgateway-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agentgateway-agentgateway-system-local
subjects:
  - kind: ServiceAccount
    name: agentgateway
    namespace: agentgateway-system
