apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agentgateway-agentgateway-system-local
  namespace: agentgateway-system
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - patch
      - update
