apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    agentgateway: agentgateway
    app.kubernetes.io/instance: agentgateway
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: agentgateway
    app.kubernetes.io/version: 1.5.0
    helm.sh/chart: agentgateway-1.5.0
  name: agentgateway
  namespace: agentgateway-system
