apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: openebs-zfs-node
    chart: zfs-localpv-2.11.1
    heritage: Helm
    name: openebs-zfs-node
    openebs.io/component-name: openebs-zfs-node
    openebs.io/version: 2.11.1
    release: openebs
    role: openebs-zfs
  name: openebs-zfs-driver-registrar-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openebs-zfs-driver-registrar-role
subjects:
  - kind: ServiceAccount
    name: openebs-zfs-node-sa
    namespace: openebs
