apiVersion: v1
data:
  zfs: |
    #!/bin/sh
    if [ -x /host/sbin/zfs ]; then
      chroot /host /sbin/zfs "$@"
    elif [ -x /host/usr/sbin/zfs ]; then
      chroot /host /usr/sbin/zfs "$@"
    else
      chroot /host "zfs" "$@"
    fi
kind: ConfigMap
metadata:
  labels:
    app: openebs-zfs-node
    chart: zfs-localpv-2.11.1
    heritage: Helm
    name: openebs-zfs-node
    openebs.io/component-name: openebs-zfs-node
    openebs.io/version: 2.11.1
    release: openebs
    role: openebs-zfs
  name: openebs-zfspv-bin
  namespace: openebs
