apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: openebs-zfs-node
    chart: zfs-localpv-2.11.1
    heritage: Helm
    name: openebs-zfs-node
    openebs.io/component-name: openebs-zfs-node
    openebs.io/version: 2.11.1
    release: openebs
    role: openebs-zfs
  name: openebs-zfs-node-sa
  namespace: openebs
