apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: openebs-zfs-controller
    chart: zfs-localpv-2.11.1
    component: openebs-zfs-controller
    heritage: Helm
    openebs.io/component-name: openebs-zfs-controller
    openebs.io/version: 2.11.1
    release: openebs
    role: openebs-zfs
  name: openebs-zfs-controller-sa
  namespace: openebs
