cephClusterSpec:
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.2
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    count: 2
    allowMultiplePerNode: false
    modules:
      - name: rook
        enabled: true
  dashboard:
    enabled: true
    ssl: false
storage:
  allowDeviceClassUpdate: false
  allowOsdCrushWeightUpdate: false
  scheduleAlways: false
  onlyApplyOSDPlacement: false
csi:
  readAffinity:
    enabled: false
  cephfs:
