---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 3
  db:
    vendor: postgres
    host: postgres-rw.keycloak.svc.cluster.local
    usernameSecret:
      name: postgres-app
      key: username
    passwordSecret:
      name: postgres-app
      key: password
  http:
    httpEnabled: true
  hostname:
    hostname: "https://sso.scarey.me"
    admin: "https://sso.apps.int.scarey.me"
  ingress:
    enabled: false
  bootstrapAdmin:
    user:
      secret: keycloak-infisical
