---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: keycloak-infisical
  data:
    - secretKey: username
      remoteRef:
        key: KEYCLOAK_ADMIN_USERNAME
    - secretKey: password
      remoteRef:
        key: KEYCLOAK_ADMIN_PASSWORD
