---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - cozystackresourcedefinition.yaml

  # Enable this once Cozystack's new dashboard is available
  #- marketplacepanel.yaml
