---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nfs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: nfs
  data:
    - secretKey: driver-config-file.yaml
      remoteRef:
        key: /democratic-csi/NFS_CONFIG
