---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: homelab
  namespace: cozy-public
spec:
  url: https://github.com/scareyo/homelab
  ref:
    branch: main
  interval: 1m0s
  timeout: 60s
