---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-controller
  namespace: tenant-root
spec:
  force: false
  interval: 10m0s
  path: ./platform/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
