apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: "1"
  labels:
    app.kubernetes.io/component: gpu-operator
    app.kubernetes.io/instance: gpu-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gpu-operator
    app.kubernetes.io/version: v26.3.0
    helm.sh/chart: gpu-operator-v26.3.0
  name: gpu-operator-upgrade-crd
  namespace: nvidia
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: gpu-operator
        app.kubernetes.io/instance: gpu-operator
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: gpu-operator
        app.kubernetes.io/version: v26.3.0
        helm.sh/chart: gpu-operator-v26.3.0
      name: gpu-operator-upgrade-crd
    spec:
      containers:
        - args:
            - apply
            - --filepath=/opt/gpu-operator/nvidia.com_clusterpolicies.yaml
            - --filepath=/opt/gpu-operator/nvidia.com_nvidiadrivers.yaml
            - --filepath=/opt/gpu-operator/nfd-api-crds.yaml
          command:
            - /usr/bin/manage-crds
          image: dev.vegapunk.cloud/scarey/gpu-operator:4485e9d4b589089370819bddb2cfa396cdd12b78
          imagePullPolicy: IfNotPresent
          name: upgrade-crd
      restartPolicy: OnFailure
      serviceAccountName: gpu-operator-upgrade-crd-hook-sa
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Equal
          value: ""
