---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudflare-api-token
  data:
    - secretKey: token
      remoteRef:
        key: /cloudflare/API_TOKEN
