---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: cozy-cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: cloudflare-api-token-secret
  data:
    - secretKey: api-token
      remoteRef:
        key: /cloudflare/API_TOKEN
