---
configs:
  cm:
    url: "https://argocd.apps.int.scarey.me"
    oidc.config: |
      name: Keycloak
      issuer: https://sso.scarey.me/realms/external
      clientID: argocd
      clientSecret: $oidc.keycloak.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
  rbac:
    policy.csv: |
      g, argocd_admin, role:admin
  params:
    server.insecure: true
