---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: oidc
  data:
    - secretKey: client_id
      remoteRef:
        key: /monitoring/GRAFANA_OIDC_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: /monitoring/GRAFANA_OIDC_CLIENT_SECRET
