---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: default
  labels:
    bgp: default
spec:
  blocks:
    - start: 10.10.21.2
      stop: 10.10.21.99
  allowFirstLastIPs: No
  #serviceSelector:
  #  matchLabels:
  #    gateway.networking.k8s.io/gateway-name: internal
