---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - default-bgpadvertisement.yaml
  - default-bgpclusterconfig.yaml
  - default-bgppeerconfig.yaml
  - default-ippool.yaml
  - hubble-httproute.yaml
  - internal-gatewayclass.yaml
  - internal-gatewayclassconfig.yaml
