---
- name: Configure Cozystack
  hosts: seraphim
  connection: local
  run_once: true
  environment:
    KUBECONFIG: "{{ cozystack_kubeconfig }}"
  tasks:
    - name: Create External Secrets Namespace
      kubernetes.core.k8s:
        name: external-secrets
        api_version: v1
        kind: Namespace
        state: present

    - name: Add Infisical secret
      kubernetes.core.k8s:
        state: present
        name: infisical-credentials
        namespace: external-secrets
        api_version: v1
        kind: Secret
        definition:
          stringData:
            clientId: "{{ cozystack_infisical_client_id }}"
            clientSecret: "{{ cozystack_infisical_client_secret }}"

    - name: Create Flux CD GitRepository
      kubernetes.core.k8s:
        state: present
        src: "{{ cozystack_config_dir }}/config/fluxcd/homelab-gitrepository.yaml"

    - name: Create Flux CD system Kustomization
      kubernetes.core.k8s:
        state: present
        src: "{{ cozystack_config_dir }}/config/fluxcd/system-kustomization.yaml"

    - name: Create Flux CD apps Kustomization
      kubernetes.core.k8s:
        state: present
        src: "{{ cozystack_config_dir }}/config/fluxcd/apps-kustomization.yaml"

    - name: Create Flux CD platform config Kustomization
      kubernetes.core.k8s:
        state: present
        src: "{{ cozystack_config_dir }}/config/fluxcd/config-kustomization.yaml"
