---
- name: Deploy nami
  hosts: localhost
  vars:
    secrets: "{{ lookup('file','secrets.json') | from_json }}"
  roles:
    - role: pxe
      vars:
        pxe_harvester_token: "{{ secrets.harvester.token }}"
        pxe_harvester_password: "{{ secrets.harvester.password }}"
        pxe_harvester_version: "v1.3.1"
        pxe_harvester_mgmt_interface: "eno2"
        pxe_harvester_vip: "10.0.20.20"
        pxe_harvester_vip_mac: "da:50:09:ec:51:83"
        pxe_harvester_osdisk: "/dev/disk/by-id/ata-KINGSTON_SA400S37240G_50026B7783F66D6B"
        pxe_harvester_datadisk: "/dev/disk/by-id/nvme-KINGSTON_SNV2S1000G_50026B77859C17C2"
  tasks:
    - name: Set persistent boot device to Hdd
      community.general.redfish_command:
        category: Systems
        command: EnableContinuousBootOverride
        resource_id: System.Embedded.1
        bootdevice: "Pxe"
        baseuri: "10.0.10.50"
        username: "{{ secrets.idrac.username }}"
        password: "{{ secrets.idrac.password }}"

    - name: Set one-time boot device to Pxe
      community.general.redfish_command:
        category: Systems
        command: SetOneTimeBoot
        resource_id: System.Embedded.1
        bootdevice: "Pxe"
        baseuri: "10.0.10.50"
        username: "{{ secrets.idrac.username }}"
        password: "{{ secrets.idrac.password }}"

    - name: Get default system info
      community.general.redfish_info:
        category: Systems
        baseuri: "10.0.10.50"
        username: "{{ secrets.idrac.username }}"
        password: "{{ secrets.idrac.password }}"
      register: result

    - name: Restart system power
      community.general.redfish_command:
        category: Systems
        command: PowerReboot
        resource_id: System.Embedded.1
        baseuri: "10.0.10.50"
        username: "{{ secrets.idrac.username }}"
        password: "{{ secrets.idrac.password }}"
      when: result.redfish_facts.system.entries[0][1].PowerState != "Off"

    - name: Turn system power on
      community.general.redfish_command:
        category: Systems
        command: PowerOn
        resource_id: System.Embedded.1
        baseuri: "10.0.10.50"
        username: "{{ secrets.idrac.username }}"
        password: "{{ secrets.idrac.password }}"
      when: result.redfish_facts.system.entries[0][1].PowerState == "Off"
