---
# ---------------------------------------------------------------------------- #
# MS-01 Mini PCs
# ---------------------------------------------------------------------------- #
ms01:
  hosts:
    s-snake:
    s-hawk:
    s-bear:
    s-shark:

# ---------------------------------------------------------------------------- #
# Hetzner Cloud VMs
# ---------------------------------------------------------------------------- #
cloud:
  hosts:
    zeus:

# ---------------------------------------------------------------------------- #
# Seraphim Cluster
# ---------------------------------------------------------------------------- #
seraphim:
  children:
    control:
      hosts:
        s-snake:
        s-hawk:
        s-bear:
    worker:
      hosts:
        s-shark:
        zeus:
