---
# ---------------------------------------------------------------------------- #
# Seraphim - Talos Linux cluster
# ---------------------------------------------------------------------------- #
seraphim:
  hosts:
    s-snake:
      ansible_host: 10.10.20.11
      mac_address: "58:47:ca:78:ea:6d"
    s-hawk:
      ansible_host: 10.10.20.12
      mac_address: "58:47:ca:78:df:35"
    s-bear:
      ansible_host: 10.10.20.13
      mac_address: "58:47:ca:78:e3:ad"
    s-shark:
      ansible_host: 10.10.20.14
      mac_address: "58:47:ca:78:dc:b5"

bootstrap:
  hosts:
    s-snake:

seraphim_control:
  hosts:
    s-snake:
    s-hawk:
    s-bear:

seraphim_worker:
  hosts:
    s-shark:

# ---------------------------------------------------------------------------- #
# zeus - External gateway hosted on Hetzner
# ---------------------------------------------------------------------------- #
gateway:
  hosts:
    zeus:
      ansible_host: 178.156.140.63
      ansible_python_interpreter: "/usr/bin/python3"
