# Playbook: Create Cozystack platform
# Installs Cozystack on bare-metal MS-01 servers
---
- name: Run PXE server
  hosts: ms01
  connection: local
  run_once: true
  environment:
    AMTCLI_USERNAME: "{{ amt_username }}"
    AMTCLI_PASSWORD: "{{ amt_password }}"
  pre_tasks:
    - name: Get AMT info
      ansible.builtin.shell: |
        set -e -o pipefail
        amtcli info {{ amt_host }} | yq .state
      changed_when: false
      register: cmd
      retries: 5
      until: cmd.stdout == 'Off'
  roles:
    - role: pxe
  tasks:
    - name: Set hosts to boot from PXE
      ansible.builtin.command: "amtcli boot pxe {{ amt_host }}"
      changed_when: true
      register: cmd
      retries: 5
      until: cmd.rc == 0

    - name: Start hosts
      ansible.builtin.command: "amtcli on {{ amt_host }}"
      changed_when: true
      register: cmd
      retries: 5
      until: cmd.rc == 0

- name: Generate talosconfig
  hosts: seraphim
  connection: local
  run_once: true
  tasks:
    - name: Generate talosconfig
      ansible.builtin.command:
        cmd: >
          talosctl gen config
            --with-secrets secrets.yaml
            --output-types talosconfig
            --output {{ inventory_dir }}/../.talos/talosconfig
            --force
            seraphim https://api.vegapunk.cloud:6443
        chdir: "{{ cozystack_cluster_dir }}"
      changed_when: true

- name: Install Cozystack
  hosts: seraphim
  connection: local
  environment:
    KUBECONFIG: "{{ cozystack_kubeconfig }}"
  roles:
    - role: cozystack
