# Playbook: Create Cozystack platform
# Installs Cozystack on bare-metal MS-01 servers
---
- name: Run PXE server
  hosts: ms01
  connection: local
  run_once: true
  roles:
    - role: pxe

- name: Boot machines to PXE
  hosts: ms01
  connection: local
  environment:
    AMTCLI_USERNAME: "{{ amt_username }}"
    AMTCLI_PASSWORD: "{{ amt_password }}"
  pre_tasks:
    - name: Get AMT info
      ansible.builtin.shell: |
        set -e -o pipefail
        amtcli info {{ amt_host }} | yq .state
      changed_when: false
      register: cmd
      retries: 5
      until: cmd.stdout == 'Off'
  tasks:
    - name: Set hosts to boot from PXE
      ansible.builtin.command: "amtcli boot pxe {{ amt_host }}"
      changed_when: true
      register: cmd
      retries: 5
      until: cmd.rc == 0

    - name: Start hosts
      ansible.builtin.command: "amtcli on {{ amt_host }}"
      changed_when: true
      register: cmd
      retries: 5
      until: cmd.rc == 0

- name: Install Cozystack
  hosts: seraphim
  connection: local
  roles:
    - role: cozystack
