# Playbook: Create zeus
# Provisions and configures a Wiredoor server on an hcloud VPS
---
- name: Provision Cloud Machines
  hosts: localhost
  connection: local
  run_once: true
  tasks:
    - name: Create Zeus
      hetzner.hcloud.server:
        name: zeus
        api_token: "{{ hcloud_api_token }}"
        server_type: cpx11
        image: alma-10
        location: ash
        ipv4: zeus
        user_data: |
          #cloud-config
          users:
            - name: {{ ansible_user_id }}
              sudo: ALL=(ALL) NOPASSWD:ALL
              shell: /bin/bash
              groups: wheel
              ssh_authorized_keys:
                - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIChdQW4k6/5G12/6y68bH0QBeuvL9tb2uVAi/ILzfxCH
        state: started
      register: result

    - name: Add zeus to inventory
      ansible.builtin.add_host:
        name: "{{ result.hcloud_server.ipv4_address }}"
        groups: wiredoor
        wiredoor_admin_email: "{{ wiredoor_admin_email }}"
        wiredoor_admin_password: "{{ wiredoor_admin_password }}"
        wiredoor_vpn_host: "{{ wiredoor_vpn_host }}"

    - name: Remove previous instances of zeus from SSH known hosts
      ansible.builtin.known_hosts:
        name: "{{ result.hcloud_server.ipv4_address }}"
        state: absent

- name: Harden zeus
  hosts: wiredoor
  become: true
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
  vars:
    sysctl_overwrite:
      net.ipv4.ip_forward: 1
      net.ipv4.ip_unprivileged_port_start: 80
    # Needed for ssh hardening el10
    ssh_host_keys_group: root

- name: Configure dnf-automatic
  become: true
  hosts: wiredoor
  vars:
    dnf_automatic_upgrade_type: default
    dnf_automatic_reboot: true
    dnf_automatic_reboot_OnCalendar: "04:00" # noqa: var-naming
  roles:
    - exploide.dnf-automatic

- name: Install Wiredoor
  hosts: wiredoor
  roles:
    - wiredoor
