---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rclone-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: rclone-secret
  data:
    - secretKey: remote
      remoteRef:
        key: RCLONE_REMOTE
    - secretKey: remotePath
      remoteRef:
        key: RCLONE_REMOTE_PATH
    - secretKey: sftp-host
      remoteRef:
        key: RCLONE_HOST
    - secretKey: sftp-user
      remoteRef:
        key: RCLONE_USER
    - secretKey: sftp-pass
      remoteRef:
        key: RCLONE_PASS
