---
vms_redhat_username: "{{ lookup('scareyo.infisical.infisical', 'redhat_username', env='prod') }}"
vms_redhat_password: "{{ lookup('scareyo.infisical.infisical', 'redhat_password', env='prod') }}"
