---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wiredoor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: wiredoor-secrets
    creationPolicy: Merge
  data:
    - secretKey: TOKEN
      remoteRef:
        key: /wiredoor/SERAPHIM_TOKEN
