#---
#configs:
#  cm:
#    url: "https://argocd.apps.int.scarey.me"
#    oidc.config: |
#      name: SSO
#      issuer: https://sso.scarey.me/application/o/argocd/
#      clientID: $oauth_client_id
#      clientSecret: $oauth_client_secret
#      requestedScopes: ["openid", "profile", "email", "groups"]
#    resource.exclusions: |
#      - apiGroups:
#        - "velero.io"
#        kinds:
#        - Backup
#        clusters:
#        - "*"
#    accounts.readonly: apiKey
#  rbac:
#    policy.csv: |
#      g, argocd-admin, role:admin
#      g, argocd-readonly, role:readonly
#  params:
#    server.insecure: true
#global:
#  addPrometheusAnnotations: true
#applicationSet:
#  metrics:
#    enabled: true
#controller:
#  metrics:
#    enabled: true
#dex:
#  metrics:
#    enabled: true
#notifications:
#  metrics:
#    enabled: true
#repoServer:
#  metrics:
#    enabled: true
#server:
#  metrics:
#    enabled: true
