- name: Ensure requirements in place
  package:
    name:
      - cockpit-storaged
    state: present

- name: Check for existing RAID device
  stat:
    path: "{{ raid_device }}"
  register: stat_raid_device

- name: Assemble the RAID device
  shell: mdadm --assemble {{ raid_device }} {% for disk in disks %}{{ disk }} {% endfor %}
  when: not stat_raid_device.stat.exists

- name: Mount RAID storage device
  ansible.posix.mount:
    path: /mnt/nami
    src: /dev/md/nami1
    fstype: xfs
    state: mounted

- name: Create NFS shares
  include_role:
    name: geerlingguy.nfs
  vars:
    nfs_exports: "{{ nfs }}"
