- name: Ensure requirements in place
  ansible.builtin.package:
    name:
      - cockpit-storaged
    state: present

- name: Check for existing RAID device
  ansible.builtin.stat:
    path: "{{ nas_raid_device }}"
  register: stat_raid_device

- name: Mount RAID storage device
  ansible.posix.mount:
    path: /mnt/nami
    src: "{{ nas_raid_device }}"
    fstype: xfs
    state: mounted
  when: not stat_raid_device.stat.exists

- name: Create NFS shares
  ansible.builtin.include_role:
    name: geerlingguy.nfs
  vars:
    nfs_exports: "{{ nas_exports }}"
  when: not stat_raid_device.stat.exists
