- name: Ensure requirements in place
  package:
    name:
      - cockpit-storaged
    state: present

- name: Check for existing RAID device
  stat:
    path: "{{ raid_device }}"
  register: stat_raid_device

- name: Mount RAID storage device
  ansible.posix.mount:
    path: /mnt/nami
    src: "{{ raid_device }}"
    fstype: xfs
    state: mounted
  when: not stat_raid_device.stat.exists

- name: Create NFS shares
  include_role:
    name: geerlingguy.nfs
  vars:
    nfs_exports: "{{ exports }}"
  when: not stat_raid_device.stat.exists
