---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hcloud
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
  - secretKey: token
    remoteRef:
      key: 9191e178-960d-4f52-b0fb-b31f003947c0
