---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: postgres-app
    creationPolicy: Merge
  data:
    - secretKey: db-encryption-key
      remoteRef:
        key: /homarr/DB_ENCRYPTION_KEY
