---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: auth-oidc-secret
  data:
    - secretKey: oidc-client-id
      remoteRef:
        key: /homarr/OIDC_CLIENT_ID
    - secretKey: oidc-client-secret
      remoteRef:
        key: /homarr/OIDC_CLIENT_SECRET
