---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-helm-charts
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: nixos/nix:2.28.2
              command:
                - /bin/sh
                - -c
                - nix-shell -p renovate --impure --command "renovate scareyo/helm-charts"
              env:
                - name: LOG_LEVEL
                  value: debug
              envFrom:
                - secretRef:
                    name: renovate
                - configMapRef:
                    name: renovate
          restartPolicy: Never
