---
- name: Setup hypervisors
  hosts: hypervisors
  remote_user: root

  pre_tasks:
    - name: Ensure requirements in place
      ansible.builtin.package:
        name:
          - cockpit-machines
          - cockpit-pcp
          - dnf-automatic
          - libvirt
          - qemu-kvm
          - virt-install
          - virt-viewer
        state: present

    - name: Start and enable Cockpit
      ansible.builtin.systemd:
        enabled: true
        state: started
        name: cockpit.socket

    - name: Start and enable pmlogger
      ansible.builtin.systemd:
        enabled: true
        state: started
        name: pmlogger.service

    - name: Create a network bridge
      community.general.nmcli:
        type: bridge
        conn_name: br0
        ifname: br0
        ip4: "10.0.20.10/24"
        gw4: "10.0.20.1"
        state: present

    - name: Create bridge slave on eno1
      community.general.nmcli:
        type: bridge-slave
        conn_name: eno1
        ifname: eno1
        slave_type: bridge
        master: br0
        hairpin: false
        state: present

  roles:
    - role: nas
      vars:
        raid_device: /dev/md/nami
        exports: []

    - role: libvirt
      vars:
        command: new-pool
        pools:
          - name: default
            type: dir
            path: "/mnt/nami/system/vm"
