---
- name: Register RHEL systems
  hosts: vms
  remote_user: cloud-user
  become: true
  tasks:
    - name: Register as user and auto-subscribe to available content
      community.general.redhat_subscription:
        state: present
        username: "{{ vms_redhat_username }}"
        password: "{{ vms_redhat_password }}"
        auto_attach: true

- name: Setup identity management
  ansible.builtin.import_playbook: vm/ipa.yaml

- name: Setup single sign-on
  ansible.builtin.import_playbook: vm/sso.yaml

- name: Setup virtual private network
  ansible.builtin.import_playbook: vm/vpn.yaml
