---
- name: Register RHEL systems
  hosts: vms
  remote_user: cloud-user
  become: true
  tasks:
    - name: Register as user and auto-subscribe to available content
      redhat_subscription:
        state: present
        username: "{{ vault_vms_redhat_username }}"
        password: "{{ vault_vms_redhat_password }}"
        autosubscribe: true

- name: Setup FreeIPA server
  hosts: ipaserver
  remote_user: cloud-user
  become: true

  roles:
    - role: freeipa.ansible_freeipa.ipaserver
      state: present

  tasks:
    - freeipa.ansible_freeipa.ipauser:
        ipaadmin_password: "{{ vault_ipa_admin_password }}"
        name: scarey
        first: Sam
        last: Carey
        email: sam@scarey.me
        password: "{{ vault_ipa_scarey_password }}"
        update_password: on_create

- name: Setup FreeIPA clients
  hosts: ipaclients
  remote_user: cloud-user
  become: true
  roles:
    - role: freeipa.ansible_freeipa.ipaclient
      state: present

- name: Setup Keycloak
  hosts: sso
  remote_user: cloud-user
  become: true
  vars:
    keycloak_quarkus_version: "21.0.1"
    keycloak_quarkus_admin_pass: "{{ vault_sso_admin_pass }}"
    ipa_admin_password: "{{ vault_ipa_admin_password }}"
  roles:
    - role: sso

- hosts: vpn
  remote_user: cloud-user
  become: true
  roles:
    - githubixx.ansible_role_wireguard
  tags: vpn
