---
- name: Setup hypervisors
  hosts: hypervisors
  remote_user: root

  pre_tasks:
    - name: Ensure requirements in place
      package:
        name:
          - cockpit-machines
          - cockpit-pcp
          - dnf-automatic
          - libvirt
          - qemu-kvm
          - virt-install
          - virt-viewer
        state: present

    - name: Generate an SSH key for root user
      community.crypto.openssh_keypair:
        path: /root/.ssh/id_rsa
      register: root_id_rsa

    - name: Add root user public key to ssh_authorized_keys
      set_fact:
        ssh_authorized_keys: "{{ ssh_authorized_keys + ['{{ root_id_rsa.public_key }}'] }}"

    - name: Start and enable Cockpit
      ansible.builtin.systemd:
        enabled: yes
        state: started
        name: cockpit.socket

    - name: Start and enable pmlogger
      ansible.builtin.systemd:
        enabled: yes
        state: started
        name: pmlogger.service

    - name: Create a network bridge
      community.general.nmcli:
        type: bridge
        conn_name: br0
        ifname: br0
        ip4: "10.0.20.10/24"
        gw4: "10.0.20.1"
        state: present

    - name: Create bridge slave on eno1
      community.general.nmcli:
        type: bridge-slave
        conn_name: eno1
        ifname: eno1
        master: br0
        hairpin: no
        state: present

  roles:
    - role: nas
      vars:
        raid_device: /dev/md/nami
        disks:
          - /dev/disk/by-partuuid/22c80b47-9a62-46c1-80d7-d7c38b0de051
          - /dev/disk/by-partuuid/047ca121-f16f-430b-9cb3-16b6241f900a
          - /dev/disk/by-partuuid/5a15b503-19f8-451a-9900-09c68e5fb77e
          - /dev/disk/by-partuuid/e87b0190-9617-48d6-baee-0ec4f603590e
          - /dev/disk/by-partuuid/55a11832-ba43-4807-aa44-b9ffcf513c3f
          - /dev/disk/by-partuuid/7224833f-2615-4aaa-b2d8-630a2f8ee11c
          - /dev/disk/by-partuuid/aeede774-70fd-4798-b827-f7c601695e12
          - /dev/disk/by-partuuid/1f2ae49e-4a22-4835-9da6-2d09fb6680eb
      nfs: []

    - role: libvirt
      vars:
        command: new-pool
        pools:
          - name: default
            type: dir
            path: "/mnt/nami/system/vm"
