---
- name: Setup hypervisors
  hosts: hypervisors
  remote_user: root

  pre_tasks:
    - name: Ensure requirements in place
      package:
        name:
          - cockpit-machines
          - cockpit-pcp
          - dnf-automatic
        state: present

    - name: Generate an SSH key for root user
      community.crypto.openssh_keypair:
        path: /root/.ssh/id_rsa
      register: root_id_rsa

    - name: Add root user public key to ssh_authorized_keys
      set_fact:
        ssh_authorized_keys: "{{ ssh_authorized_keys + ['{{ root_id_rsa.public_key }}'] }}"

    - name: Start and enable Cockpit
      ansible.builtin.systemd:
        enabled: yes
        state: started
        name: cockpit.socket

    - name: Start and enable pmlogger
      ansible.builtin.systemd:
        enabled: yes
        state: started
        name: pmlogger.service

    - name: Enable IOMMU
      lineinfile:
        path: /etc/default/grub
        backrefs: true
        regexp: '^(GRUB_CMDLINE_LINUX=(?!.*intel_iommu=on)\"[^\"]+)(\")'
        line: '\1 intel_iommu=on\2'
      notify:
        - Regenerate GRUB config
        - Restart

    - name: Create a network bridge
      community.general.nmcli:
        type: bridge
        conn_name: br0
        ifname: br0
        ip4: "10.0.20.10/24"
        gw4: "10.0.20.1"
        state: present

    - name: Create bridge slave on eno1
      community.general.nmcli:
        type: bridge-slave
        conn_name: eno1
        ifname: eno1
        master: br0
        hairpin: no
        state: present

  roles:
    - role: libvirt
      vars:
        command: new-pool
        pools:
          - name: local
            type: dir
            path: "/var/lib/libvirt/images"

    - role: libvirt
      vars:
        command: new-vm
        vms:
          - name: nas
            mac_address: "52:54:00:d7:20:50"
            memory: "4096"
            vcpus: "4"
            pool: "local"
            pci_devices:
              # Broadcom / LSI SAS2308 PCI-Express Fusion-MPT SAS-2 (storage controller)
              - "03:00.0"

- name: Setup NAS
  hosts: nas
  remote_user: almalinux
  become: yes
  roles: 
    - role: nas
      vars:
        raid_device: /dev/md/nami
        disks:
          - /dev/sda1
          - /dev/sdb1
          - /dev/sdc1
          - /dev/sdd1
          - /dev/sde1
          - /dev/sdf1
          - /dev/sdg1
          - /dev/sdh1
      nfs:
        - "/mnt/nami/system/vm *(rw,sync,no_root_squash)"
        
- name: Add NFS storage pool to libvirt
  hosts: hypervisors
  remote_user: root
  roles:
    - role: libvirt
      vars:
        command: new-pool
        pools:
          - name: default
            type: netfs
            nfs_host: 10.0.20.50
            nfs_path: "/mnt/nami/system/vm"
            path: "/mnt/nami/system/vm"
