---
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  annotations:
    fluxcd.controlplane.io/reconcile: enabled
    fluxcd.controlplane.io/reconcileEvery: 1h
    fluxcd.controlplane.io/reconcileTimeout: 5m
spec:
  distribution:
    version: 2.x
    registry: ghcr.io/fluxcd
  cluster:
    type: kubernetes
    size: medium
    multitenant: false
    networkPolicy: true
    domain: cluster.local
  commonMetadata:
    labels:
      app.kubernetes.io/name: flux
  sync:
    kind: GitRepository
    url: https://github.com/scareyo/homelab.git
    ref: refs/heads/main
    path: k8s/clusters/production
