---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: homepage
  data:
    - secretKey: argocd_api_key
      remoteRef:
        key: ARGOCD_READONLY_API_KEY
