---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: keycloak
  data:
    - secretKey: client_id
      remoteRef:
        key: KEYCLOAK_CLIENT_ID_GRAFANA
    - secretKey: client_secret
      remoteRef:
        key: KEYCLOAK_CLIENT_SECRET_GRAFANA
