---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocket-id
resources:
  - namespace.yaml
  - postgres-cluster.yaml
  - repository.yaml
  - release.yaml
  - pocket-id-httproute.yaml
