---
name: rook
namespace: rook-ceph
enforce: privileged
sources:
  - type: helm
    chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: v1.17.7

  - type: helm
    chart: rook-ceph-cluster
    repoURL: https://charts.rook.io/release
    targetRevision: v1.17.7

  - type: dir
    path: config
