---
cephClusterSpec:
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.3
  mgr:
    modules:
      - name: rook
        enabled: true
  dashboard:
    ssl: false
  monitoring:
    enabled: false
    exporter:
      perfCountersPrioLimit: 5
      statsPeriodSeconds: 5
  storage:
    allowDeviceClassUpdate: false
    allowOsdCrushWeightUpdate: false
    scheduleAlways: false
    onlyApplyOSDPlacement: false
  csi:
    readAffinity:
      enabled: false
    cephfs:
  healthCheck:
    daemonHealth:
    startupProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
