---
name: cilium
namespace: kube-system
sources:
  - type: helm
    chart: cilium
    repoURL: https://helm.cilium.io
    targetRevision: 1.18.0

  - type: dir
    path: config

ignoreDifferences:
  - group: ''
    kind: Secret
    name: ''
    jsonPointers:
      - /data/ca.crt
      - /data/ca.key
      - /data/tls.crt
      - /data/tls.key
