---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: "https://github.com/scareyo/homelab.git"
        revision: develop
        directories:
          - path: apps/*
          - path: apps/cilium
            exclude: true
  template:
    metadata:
      name: "{{`{{.path.basename}}`}}"
    spec:
      project: "default"
      source:
        repoURL: "https://github.com/scareyo/homelab.git"
        targetRevision: develop
        path: "{{`{{.path.path}}`}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{`{{.path.basename}}`}}"
      syncPolicy:
        automated:
          prune: true
