---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook
spec:
  project: default
  source:
    repoURL: "https://github.com/scareyo/homelab.git"
    targetRevision: develop
    path: "apps/rook"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
