---
- name: 'Check mandatory variables are defined'
  ansible.builtin.assert:
    that:
      - pxe_config["harvester"].token
      - pxe_config["harvester"].version is defined
      - pxe_config["harvester"].vip is defined
      - pxe_config["harvester"].vip_mac is defined

- name: Download Harvester ISO
  ansible.builtin.get_url:
    url: "{{ pxe_harvester_iso_url }}"
    dest: "{{ pxe_http_path }}/harvester.iso"
    checksum: "{{ pxe_harvester_iso_checksum }}"
    mode: "0644"
  run_once: true

- name: Download Harvester kernel
  ansible.builtin.get_url:
    url: "{{ pxe_harvester_kernel_url }}"
    dest: "{{ pxe_http_path }}/vmlinuz"
    checksum: "{{ pxe_harvester_kernel_checksum }}"
    mode: "0644"
  run_once: true

- name: Download Harvester initrd
  ansible.builtin.get_url:
    url: "{{ pxe_harvester_initrd_url }}"
    dest: "{{ pxe_http_path }}/initrd"
    checksum: "{{ pxe_harvester_initrd_checksum }}"
    mode: "0644"
  run_once: true

- name: Download Harvester rootfs
  ansible.builtin.get_url:
    url: "{{ pxe_harvester_rootfs_url }}"
    dest: "{{ pxe_http_path }}/rootfs"
    checksum: "{{ pxe_harvester_rootfs_checksum }}"
    mode: "0644"
  run_once: true

- name: Generate Harvester config
  ansible.builtin.template:
    src: harvester.yaml.j2
    dest: "{{ pxe_http_path }}/config.{{ mac_address }}.yaml"
    mode: "0644"
