---
- name: 'Check mandatory variables are defined'
  ansible.builtin.assert:
    that:
      - pxe_config["talos"].config in ["control", "worker"]
      - pxe_config["talos"].secrets is defined
      - pxe_config["talos"].cluster_name is defined
      - pxe_config["talos"].cluster_endpoint is defined
      - pxe_config["talos"].osdisk is defined

- name: Download Talos kernel
  ansible.builtin.get_url:
    url: "{{ pxe_talos_kernel_url }}"
    dest: "{{ pxe_http_path }}/vmlinuz"
    mode: "0644"
  run_once: true

- name: Download Talos initrd
  ansible.builtin.get_url:
    url: "{{ pxe_talos_initrd_url }}"
    dest: "{{ pxe_http_path }}/initrd"
    mode: "0644"
  run_once: true

- name: Generate Talos config
  ansible.builtin.command:
    chdir: "{{ pxe_http_path }}"
    cmd: "talosctl gen config --with-secrets {{ pxe_config['talos'].secrets }} {{ pxe_config['talos'].cluster_name }} {{ pxe_config['talos'].cluster_endpoint }} --install-disk {{ pxe_config['talos'].osdisk }} --force"
  run_once: true

- name: Generate Talos patch file
  ansible.builtin.template:
    src: talos.patch.j2
    dest: "{{ pxe_http_path }}/{{ mac_address}}.patch"
    mode: "0644"

- name: Patch Talos control plane config
  ansible.builtin.command:
    chdir: "{{ pxe_http_path }}"
    cmd: "talosctl machineconfig patch {{ pxe_http_path }}/controlplane.yaml --patch @{{ pxe_http_path }}/{{ mac_address}}.patch --output {{ pxe_http_path }}/config.{{ mac_address}}.yaml"
  when: pxe_config["talos"].config == "control"

- name: Patch Talos worker config
  ansible.builtin.command:
    chdir: "{{ pxe_http_path }}"
    cmd: "talosctl machineconfig patch {{ pxe_http_path }}/worker.yaml --patch @{{ pxe_http_path }}/{{ mac_address }}.patch --output {{ pxe_http_path }}/config.{{ mac_address}}.yaml"
  when: pxe_config["talos"].config == "worker"

- name: Merge default config
  ansible.builtin.command:
    chdir: "{{ pxe_http_path }}"
    cmd: "talosctl config merge ./talosconfig"
  run_once: true
